FROM amazeeio/php:7.2-cli-drupal

# We don't need the composer.lock file
# COPY composer.json composer.lock /app/

COPY composer.json /app/
COPY scripts /app/scripts
RUN composer install --no-dev
COPY . /app

# Define where the Drupal Root is located
ENV WEBROOT=web
